export enum EstadoConvenio {
  PENDIENTE = 'PENDIENTE',
  EN_PROCESO = 'EN PROCESO',
  PROCESO_DE_CONVENIO = 'PROCESO DE CONVENIO',
  REUNION_AGENDADA = 'REUNIÓN AGENDADA',
  CONVENIO_FIRMADO = 'CONVENIO FIRMADO',
  CANCELADO = 'CANCELADO',
}
