export enum TipoConvenio {
  GOBIERNO_REGIONAL = 'GOBIERNO_REGIONAL',
  MUNICIPALIDAD = 'MUNICIPALIDAD',
  MINISTERIO = 'MINISTERIO',
  EMPRESA_PRIVADA = 'EMPRESA_PRIVADA',
  ONG = 'ONG',
  UGEL = 'UGEL',
  PERSONA = 'PERSONA',
  ORGANISMO_PUBLICO = 'ORGANISMO_PUBLICO',
  ASOCIACION_CIVIL = 'ASOCIACION_CIVIL',
  VENUE = 'VENUE',
}
